functions:
  worker:
    handler: handler.worker
    events:
      - http:
          path: /stac/search
          method: post
    layers:
    - arn:aws:lambda:us-east-1:725820063953:layer:cognition-datasources:6

provider:
  environment:
    SPATIALINDEX_C_LIBRARY: /opt/lib/libspatialindex_c.so.4
  iamRoleStatementsName: cognition-datasources-role
  iamRoleStatements:
    - Action:
        - lambda:InvokeFunction
        - s3:*
      Effect: Allow
      Resource:
        - arn:aws:lambda:*
        - arn:aws:s3:::*

  name: aws
  region: us-east-1
  runtime: python3.6
  stage: dev
service: cognition-datasources-test-layer

package:
  artifact: lambda-service-package.zip